# Generated by Django 5.1.1 on 2024-09-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_comment_like_post_delete_comments_delete_posts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
