# Generated by Django 5.1.1 on 2024-09-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_post_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_at']},
        ),
    ]
